export const sampleInvoices = [
  {
    id: '1',
    clientName: 'Acme Corporation',
    amount: '$2,450.00',
    dueDate: '2024-02-15',
    status: 'paid' as const,
    items: [
      { name: 'Web Development', quantity: 1, price: '$2,000.00' },
      { name: 'Domain Setup', quantity: 1, price: '$450.00' },
    ],
    backgroundColor: '#f0f9ff',
    accentColor: '#0ea5e9',
    imageSource: require('../assets/onboarding/largeversiononinv1.png'),
  },
  {
    id: '2',
    clientName: 'Tech Solutions Ltd',
    amount: '$1,850.00',
    dueDate: '2024-02-20',
    status: 'pending' as const,
    items: [
      { name: 'Mobile App Design', quantity: 1, price: '$1,500.00' },
      { name: 'User Testing', quantity: 1, price: '$350.00' },
    ],
    backgroundColor: '#fef3c7',
    accentColor: '#f59e0b',
    imageSource: require('../assets/onboarding/Untitled design (17).png'),
  },
  {
    id: '3',
    clientName: 'Creative Agency',
    amount: '$3,200.00',
    dueDate: '2024-02-25',
    status: 'overdue' as const,
    items: [
      { name: 'Brand Identity', quantity: 1, price: '$2,500.00' },
      { name: 'Logo Design', quantity: 1, price: '$700.00' },
    ],
    backgroundColor: '#fef2f2',
    accentColor: '#ef4444',
    imageSource: require('../assets/onboarding/Untitled design (18).png'),
  },
  {
    id: '4',
    clientName: 'Startup Inc',
    amount: '$1,650.00',
    dueDate: '2024-03-01',
    status: 'paid' as const,
    items: [
      { name: 'Website Redesign', quantity: 1, price: '$1,200.00' },
      { name: 'SEO Optimization', quantity: 1, price: '$450.00' },
    ],
    backgroundColor: '#f0fdf4',
    accentColor: '#22c55e',
    imageSource: require('../assets/onboarding/Untitled design (19).png'),
  },
  {
    id: '5',
    clientName: 'Enterprise Corp',
    amount: '$4,750.00',
    dueDate: '2024-03-05',
    status: 'pending' as const,
    items: [
      { name: 'System Integration', quantity: 1, price: '$3,500.00' },
      { name: 'Training Sessions', quantity: 1, price: '$1,250.00' },
    ],
    backgroundColor: '#faf5ff',
    accentColor: '#a855f7',
    imageSource: require('../assets/onboarding/Untitled design (20).png'),
  },
]; 